version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --experimental-modules
    command: ['node', 'server.js']
